version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: moji-app-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://moji:moji123@postgres:5432/moji_db
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - postgres
      - redis
    networks:
      - moji-dev-network

  postgres:
    image: postgres:15-alpine
    container_name: moji-postgres-dev
    environment:
      POSTGRES_USER: moji
      POSTGRES_PASSWORD: moji123
      POSTGRES_DB: moji_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - moji-dev-network

  redis:
    image: redis:7-alpine
    container_name: moji-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - moji-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  moji-dev-network:
    driver: bridge